version: '3.9'

services:
  app:
    build: .
    container_name: insalata-art
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./site:/app/site
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=production

volumes:
  node_modules:

